server:
  port: 8081
spring:
  application:
      name: VEHICLE-SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ksandeepa07/AAD-CW/tree/master/config_server
          username: Ksandeepa07
          password: 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
          default-label: "master"












#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/