server:
  port: 8080
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      mvc:
        routes:
          - id: VEHICLE-SERVICE
            uri: lb://VEHICLE-SERVICE
            predicates:
              - Path=/api/v1/vehicles/**

          - id: USER-SERVICE
            uri: lb://USER-SERVICE
            predicates:
              - path=/api/v1/users/**

          - id: TICKET-SERVICE
            uri: lb://TICKET-SERVICE
            predicates:
              - path=/api/v1/tickets/**

          - id: PAYMENT-SERVICE
            uri: lb://PAYMENT-SERVICE
            predicates:
              - path=/api/v1/payments/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        defaultZone: http://localhost:8761/eureka/